name: Talend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Unzip Talend Job
      run: |
        Expand-Archive -Path TalendTesting.zip -DestinationPath TalendTesting
      
    - name: Run Talend Job
      run: |
        cd TalendTesting
        .\TalendTesting_run.bat
